config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts do
    collection do
      post :import
    end
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PHONE_REGEX = /\A[(][+]\d{2}+[)]\s\d{3}[ -]\d{3}[ -]\d{2}[ -]\d{2}/
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    validates :phone, presence: true, uniqueness: true, format: { with: VALID_PHONE_REGEX }
    validates :birthday, presence: true
    validates :credit_card, presence: true
    validates :franchise, presence: true
    validates :address, presence: true
    encrypts :credit_card
    belongs_to :user

    def self.assign_from_row(row, csv_headers)
        contact = Contact.where(email: row[:email]).first_or_initialize        
        contact_fields = row.to_hash.slice(*csv_headers)
        unless CreditCardValidator::Validator.valid?(contact_fields["credit_card"])
            contact_fields["franchise"] = "unknown"
            contact.errors.add(:credit_card, "Invalid credit card number")
        else
            contact_fields["franchise"] = CreditCardValidator::Validator.card_type(contact_fields["credit_card"])
        end
        byebug
        contact.assign_attributes contact_fields
        byebug
        contact
    end
end

app/models/contact/import.rb
class Contact::Import
    include ActiveModel::Model
    attr_accessor :current_user, :file, :csv_headers, :imported_count, :field_1, :field_2, :field_3, :field_4, :field_5, :field_6

    def set_csv_headers
        @csv_headers = [@field_1, @field_2, @field_3, @field_4, @field_5, @field_6]
    end

    def process!
        @imported_count = 0
        CSV.foreach(file.path, headers: csv_headers) do |row|
            contact = Contact.assign_from_row(row, csv_headers)
            contact.user_id = @current_user.id
            byebug
            if contact.save
                @imported_count += 1
                byebug
            else
                errors.add(:base, "Line #{$.} - #{contact.errors.full_messages.join(",")}")
                byebug
            end
        end
    end

    def save
        process!
        errors.none?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
        @import = Contact::Import.new
    end

    def index
        @contacts = Contact.all
    end

    def import
        @import = Contact::Import.new contact_import_params
        @import.set_csv_headers
        @import.current_user = current_user
        if @import.csv_headers.uniq.length == @import.csv_headers.length
            if @import.save
                redirect_to contacts_path, notice: "Imported #{@import.imported_count} users"
            else
                @contact = Contact.new
                flash[:notice] = "there were errors with your CSV file"
                render :new
            end
        else
            @contact = Contact.new
            flash[:alert] = "Please avoid repeating fields"
            render :new
        end
    end 

    private 
    
    def contact_import_params
        params.permit(:file,:field_1,:field_2,:field_3,:field_4,:field_5,:field_6)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/index.html.erb
<h2>Imported contacts: </h2>
<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Birthday</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Credit card</th>
        <th>Franchise</th>
    </tr>
    <% @contacts.each do |contact|%>
        <tr>
            <th><%=contact.name %></th>
            <th><%=contact.email %></th>
            <th><%=contact.birthday %></th>
            <th><%=contact.phone %></th>
            <th><%=contact.address %></th>
            <th><%=contact.credit_card %></th>
            <th><%=contact.franchise %></th>
        </tr>
    <% end %>
</table>

app/views/contacts/new.html.erb
<h3>Choose the order of the CSV file headers:</h3>
<%= form_with  url: import_contacts_path, multipart: true do |form| %>
  <% 6.times do |field| %>
    <%= form.label "Field #{field + 1}" %>
    <%= form.select "field_#{field + 1}".to_sym, ["name", "phone", "email", "birthday", "address", "credit_card"] %>
  <% end %>
  <%= form.file_field :file %>
  <%= submit_tag "Upload" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>This is a contact importing tool</h2>
<p>Here you can import contacts with name, birthdate, phone number, address, credit card info and email contained inside a CSV file</p>

<% unless user_signed_in? %>
  <%= link_to 'Log in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% else %>
  <%= link_to 'Import CSV', new_contact_path %>
  import csv file
  <%= link_to 'Log out',  destroy_user_session_path, method: :delete, class: "nav-link" %>

<% end %>